server:
  port: 8080

spring:
  application:
    name: odm-platform-adapter-marketplace-executor
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write-dates-as-timestamps: false

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: org.opendatamesh.odm.platform.adapter.marketplace.executor.starter.controller

# Logging configuration
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ODM configuration
odm:
  product-plane:
    marketplace-service:
      active: true
      address: http://localhost:8080