package org.opendatamesh.platform.adapter.marketplace.executor.starter.resources;

import io.swagger.v3.oas.annotations.media.Schema;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;
import java.util.Map;

@Schema(description = "Request information for marketplace operations")
public class RequestRes {
    @Schema(description = "Name of the request", required = true)
    @NotBlank(message = "Request name is required")
    private String name;

    @Schema(description = "Identifier of the request, generated by the Marketplace Service", required = true)
    @NotBlank(message = "Request identifier is required")
    private String identifier;

    @Schema(description = "Provider information", required = true)
    @NotNull(message = "Provider information is required")
    private ProviderRes provider;

    @Schema(description = "Consumer information", required = true)
    @NotNull(message = "Consumer information is required")
    private ConsumerRes consumer;

    @Schema(description = "Requester information", required = true)
    @NotNull(message = "Requester information is required")
    private RequesterRes requester;

    @Schema(description = "Additional properties that can be configured dynamically")
    private Map<String, Object> properties;

    @Schema(description = "The date on which access starts to be valid", required = true)
    @NotNull(message = "Start date is required")
    private Date startDate;

    @Schema(description = "The date on which access expires", required = true)
    @NotNull(message = "End date is required")
    private Date endDate;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public ProviderRes getProvider() {
        return provider;
    }

    public void setProvider(ProviderRes provider) {
        this.provider = provider;
    }

    public ConsumerRes getConsumer() {
        return consumer;
    }

    public void setConsumer(ConsumerRes consumer) {
        this.consumer = consumer;
    }

    public RequesterRes getRequester() {
        return requester;
    }

    public void setRequester(RequesterRes requester) {
        this.requester = requester;
    }

    public Map<String, Object> getProperties() {
        return properties;
    }

    public void setProperties(Map<String, Object> properties) {
        this.properties = properties;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
} 